package com.securitymak.securitymak.model;

public enum AuditAction {

    // ---- CASE EVENTS ----
    CASE_CREATED,
    CASE_UPDATED,
    CASE_STATUS_CHANGED,
    CASE_SENSITIVITY_CHANGED,
    CASE_VIEWED,

    // ---- COMMENT EVENTS ----
    COMMENT_ADDED,
    COMMENT_DELETED,

    USER_ROLE_CHANGED,

    // ---- SECURITY EVENTS ----
    CROSS_TENANT_ACCESS_ATTEMPT,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    INSUFFICIENT_CLEARANCE_ATTEMPT,
    INVALID_STATUS_TRANSITION,

    // ---- ADMIN EVENTS ----
    ADMIN_OVERRIDE,

    USER_REGISTERED,
    USER_LOGIN,

    PASSWORD_CHANGED,

    CLEARANCE_UPDATED,

    INVITE_CREATED,
    INVITE_TERMINATED,
    INVITE_REGISTERED,
    INVITE_APPROVED,
    INVITE_REJECTED,

    USER_DISABLED,
    USER_REENABLED,

    EMAIL_BANNED,
    EMAIL_UNBANNED,

    BANNED_USER_ATTEMPTED_REGISTRATION,
    BANNED_USER_ATTEMPTED_LOGIN,

    INVALID_INVITE_TOKEN_USED,
    INVITE_EMAIL_MISMATCH,

    BAD_PASSWORD,

}