ALTER TABLE case_events
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE case_parties
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE case_documents
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE case_assignments
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
